version: '2'
services:
  app-under-the-load:
    image: app-under-the-load:0.2
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=db
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - INFLUX_HOST=influxdb
    ports:
      - "8088:8088"
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'default'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /app/docker/mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8091:8091'
    expose:
      - '8091'
    links:
      - app-under-the-load

  influxdb:
    image: influxdb:1.8.6
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - './tig/env.influxdb'
    volumes:
      - '/app/docker/grafana/data:/var/lib/influxdb'

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
      - db
    volumes:
      - './tig/telegraf.conf:/etc/telegraf/telegraf.conf:ro'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    env_file:
      - './tig/env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - '/app/docker/grafana/data:/var/lib/grafana'
